dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python3

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel_0.28.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.28.1-linux-x86_64.deb

script:
  - bazel build //...
